### ISSUE TITLE
哥们，能不能标一下Ram使用的情况？

### ISSUE THREAD

**Issue by qiansen1386** [zwh8800/xware#2]
最近想买个NAS。需要先找支持Docker的机子，然后再选RAM。他们说RAM越高，下载越好？你用的机器是 Asustor 华芸的么？xware 能运行在ARM的CPU上么？

**Comment by zwh8800** [comment]
这个主要看xware的内存占用，我这里不下载的时候在5m左右，下载的时候可能上升到十几m，总之xware不很占用内存。我的服务器开了xware、samba、ddns这几个服务，总共内存占用也就 80多m

```
              total        used        free      shared  buff/cache   available
Mem:           1.8G         82M        782M        5.9M        1.0G        1.7G
Swap:          893M          0B        893M
```

xware可以运行咋arm，但是我这个docker镜像是x86的，不能再arm上运行。因为目前 docker for arm 的生态还没做起来吧。

**Comment by qiansen1386** [comment]
秒回啊:smile:，多谢多谢。

**Comment by zwh8800** [comment]
蛤蛤，上班不很忙，给点个星呗

**Comment by qiansen1386** [comment]
吼啊
就知道你也是上班……蛤蛤。
