### ISSUE TITLE
Unraid安装不成功

### ISSUE THREAD

**Issue by invinciberry** [zwh8800/xware#4]
在unraid中docker安装后log显示如下
./monitor.sh: line 16: ./portal: cannot execute binary file: Exec format error

**Comment by zwh8800** [comment]
请确认是否x86的机器，只有cpu是x86的才能安装。arm、misp的都不可以的。

**Comment by invinciberry** [comment]
是应为系统是64位造成的么？
My mailbox is protected and cleaned by cleanfox.io
<https://www.cleanfox.io?utm_source=chrome_extension&utm_campaign=chrome_extension&utm_medium=signature>

**Comment by zwh8800** [comment]
如果是64位的系统，装了multilib-32有可能可以。这是迅雷的限制，我也无能为力

**Comment by invinciberry** [comment]
我可以安装32位VM，然后再vm里安装xware么？对于linux不是很了解，如果这样可以，哪一个版本的linux适合我呢？选择有很多，例如ubuntu，freebsd，centos什么的。
My mailbox is protected and cleaned by cleanfox.io
<https://www.cleanfox.io?utm_source=chrome_extension&utm_campaign=chrome_extension&utm_medium=signature>

**Comment by zwh8800** [comment]
ubuntu 就行

**Comment by invinciberry** [comment]
我安装了32bit ubuntu之后发现docker只支持64bit系统，请问是我哪里做错了么？
My mailbox is protected and cleaned by cleanfox.io
<https://www.cleanfox.io?utm_source=chrome_extension&utm_campaign=chrome_extension&utm_medium=signature>

**Comment by zwh8800** [comment]
emmm，你可以参考下个文章，安装一下 multilib https://askubuntu.com/questions/454253/how-to-run-32-bit-app-in-ubuntu-64-bit/454254#454254。

大概就是这几条命令：

```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386
sudo apt-get install multiarch-support
```

然后再尝试运行，如果还不行，应该是你的kernel没有开启运行32位 binary 的选项，这就不好办了

**Comment by zwh8800** [comment]
我查了一下，好像你用的 unraid 的 kernel 就不支持 32 bit 应用，好像无解了。。。

https://forums.lime-technology.com/topic/53967-unraid-kernel-with-32bit-support/

**Comment by invinciberry** [comment]
谢谢，昨晚尝试了很多不同方法，最后用
https://github.com/Xinkai/XwareDesktop/wiki/Ubuntu%E4%B8%8A%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85%E8%AF%B4%E6%98%8E中的方法在64bit
ubuntu上安装了xware，但还是没办法正常工作，迅雷提示说7月17日开始陆续停止第三方远程下载支持。现在正在尝试安装window VW。
My mailbox is protected and cleaned by cleanfox.io
<https://www.cleanfox.io?utm_source=chrome_extension&utm_campaign=chrome_extension&utm_medium=signature>

**Comment by zwh8800** [comment]
我也看到公共了，迅雷辣🐔啊

**Comment by invinciberry** [comment]
LOL,总之谢谢了！什么都不懂给你添了这么多麻烦！谢谢！
My mailbox is protected and cleaned by cleanfox.io
<https://www.cleanfox.io?utm_source=chrome_extension&utm_campaign=chrome_extension&utm_medium=signature>

**Comment by zwh8800** [comment]
哈哈，太客气了
